### PR TITLE
Binary search.

### PR DESCRIPTION
**Pull request by chriseth**
Adapted binary search logic - still needs to be tested.

### CODE REVIEW

**Comment by chriseth** [comment]
I think we have to add a `sleep 1` or something between the two `geth` calls. Perhaps executing the script can also be done already as part of the first call?

**Comment by terminaldweller** [comment]
we could add that sleep one between the two geth calls, sure, you can never be too safe.
but i think the problem with this one is already solved. 
this branch's travis.yml is behind master's travis.yml.  if we update to that we should be fine. 
go-etherem's dev branch was not playing nice on travis so i just switched us to a release branch.
also which first call do you mean?

**Comment by chriseth** [comment]
ah ok, then let me rebase.

**Comment by chriseth** [comment]
Ok, tests fail now because they take longer than 50 minutes...

**Pull request merged**
