### PR TITLE
fix: tests for geth

### PR DESCRIPTION
**Pull request by shrugs**

### CODE REVIEW

**Comment by hswick** [comment]
Finally noticing that the travis tests dont pass because it can't find /bin/test.sh, not this PRs fault. But wouldn't hurt to fix.

**Comment by sinahab** [comment]
Dope!

Notes from our convo on Slack:
- some docs around how to setup etherbase for geth
- tests fail when run with ganache (think due to the previous timeout issue)

**Comment by shrugs** [comment]
for some reason the last (12th) iteration of `should query normal case medHash==0x0 step 12` is failing; I don't think the submitter is responding correctly. Investingating

**Comment by sinahab** [comment]
LGTM. Tests pass on ganache. :)

**Pull request merged**
